name: Oliviabeauty
favicon: null
layout_spectrum: 0.98532
typography_spectrum: 0.92115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f8fe'
    - '#d3c8cc'
    - '#db9f95'
    - '#02052b'
    - '#876d67'
  brandStrength: 0.031145205488428473
  lightness: 0.32953018601983786
  saturation: 0.4886063083540648
  rhythmicContrast: 0.3104638056829572
purpose: []
